version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  # db: # 서비스 명
  #   image: mariadb:latest # 사용할 이미지
  #   container_name:  # 컨테이너 이름 설정
  #   ports:
  #     - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
  #   environment: # -e 옵션
  #     MYSQL_DATABASE: rush00
  #     MYSQL_ROOT_PASSWORD: password  # MYSQL 패스워드 설정 옵션
  #   command: # 명령어 실행
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #     - ./db/mariadb:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
  #   healthcheck:
  #       test: ["CMD", "curl", "-f", "http://localhost:3306"]
  #       interval: 30s
  #       timeout: 10s
  #       retries: 5
  front: # 컨테이너 이름
    build:
      context: ./front # 도커파일이 위치한 위치
      dockerfile: Dockerfile.dev # 도커파일 이름
    stdin_open: true # 리액트 앱을 돌리때 필요한 옵션 , 리액트앱을 끌때 필요
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true



