version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  back:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./back/Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        # networks:
            # - nesjs-network
        volumes:
            - ./back:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
  front: # 컨테이너 이름
    build:
      context: ./front # 도커파일이 위치한 위치
      dockerfile: Dockerfile # 도커파일 이름
    ports:
      - "3000:3000" # port 맵핑
    volumes: # 실시간 코드 수정을 위한 volumes 설정
      - /usr/src/app/node_modules
      - ./front:/usr/src/app
